#! /bin/sh

#---------------------------------------------------------------------
#                               detect                                
# 
# Check and see whether the current directory is subject to this
# type of revision control.
#---------------------------------------------------------------------

test -z "${FW_TRACE}" || set -x

# exit 1 => not detected
# exit 0 => detected

exit 1
